version: "3.7"
services:
  api:
    build: ./
    pull_policy: build
    restart: unless-stopped
    ports:
      - "1234:4040"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    env_file:
      - staging.env
