version: "3.7"
services:
  api:
    build: ./
    pull_policy: build
    restart: unless-stopped
    ports:
      - "420:4040" # funny
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - stack.env
