# Running "docker compose up" (active process)
# or "docker compose start" (background process)
# will setup the development database
#
# One can connect to it using your DB client
# (Rider, pqadmin, psql, ...),
# using the following parameters (see: appsettings.json):
# Host=localhost:15432; Database=gainstracker_db; Username=stoy; Password=gainstracker_docker

version: "3.7"
services:
  db:
    build: GainsTracker.CoreAPI/development/db
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: stoy
      POSTGRES_PASSWORD: gainstracker_docker
      DB_NAME: gainstracker_db
      DB_USER: stoy
      DB_PASS: gainstracker_docker
      DB_HOST: db:5432
    volumes:
      - ./GainsTracker.CoreAPI/development/postgres/docker_data:/var/lib/postgresql/data
  api:
    build: ./
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "420:4040" # funny
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file:
      - docker.env
