# Running "docker compose up" (active process)
# or "docker compose start" (background process)
# will setup the development database
#
# One can connect to it using your DB client
# (Rider, pqadmin, psql, ...),
# using the following parameters (see: appsettings.json):
# Host=localhost:15432; Database=gainstracker_db; Username=stoy; Password=postman

version: "3.7"
services:
  db:
    build: GainsTracker.Data/development/db
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: stoy
      POSTGRES_PASSWORD: gainstracker_local
      DB_PASS: gainstracker_local
      DB_NAME: gainstracker_db
      DB_USER: stoy
    volumes:
      - ./GainsTracker.Data/development/postgres/local_data:/var/lib/postgresql/data
